services:
  backend:
    build:
      context: ./back-server
    ports:
      - "3008:3008"
    volumes:
      - ./back-server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - cmsdatabase
      - toherodb
    networks:
      - cms-network

  frontend:
    build:
      context: ./front-server
    ports:
      - "8081:8081"
    volumes:
      - ./front-server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - cms-network

  cmsdatabase:
    image: postgres:17
    container_name: numdiagcmsdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: numdiagcmsdb
    ports:
      - "5436:5432"
    volumes:
      - numdiagcms-data:/var/lib/postgresql/data
    networks:
      - cms-network

  toherodb:
    image: postgres:17
    container_name: toherodb-cms-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: toherocmsdb
      # POSTGRES_ROLE: postgres
    ports:
      - "5437:5432"
    volumes:
      - toherocms-data:/var/lib/postgresql/data
    user: postgres
    networks:
      - cms-network

networks:
  cms-network:
    driver: bridge

volumes:
  numdiagcms-data:
  toherocms-data:
